### ISSUE TITLE
Modifications to the default URL structure

### ISSUE THREAD

**Issue by dwhly** [ikreymer/via#1]
Right now, I believe, the URL structure is:
http://(pywb-host)/h/http://(target-host)/(target-path)

It might be nice for simplicity to have the default simple URL be: 
http://(pywb-host)/http://(target-host)/(target-path)

A question is whether there are any modifying parameters that it might make sense to provide for in the future-- but perhaps there's another way to pass those.

**Comment by BigBlueHat** [comment]
@ikreymer could it be made to catch a regex for `http(s)` or even alphanumeric + one or more dots.

Reason for asking...check out this URL:
```
http://genius.com/www.nytimes.com/2015/01/12/business/media/pop-music-critic-leaves-the-new-yorker-to-annotate-lyrics-for-a-start-up.html
```
Cleaner URL. They drop the `http://` (if present) and apparently run through all the crazy nytimes.com redirects per issue #57 on PyWB.

Let us know how we can help. :smiley:

**Comment by ikreymer** [comment]
Yes, I think that should be doable.. I actually like the http:// personally as its easier to see url, but can be removed.. Will require a few changes on pywb but not too bad.

Redirect should fixable too.. it works on the webrecorder version:
https://webrecorder.io/preview/www.nytimes.com/2015/01/12/business/media/pop-music-critic-leaves-the-new-yorker-to-annotate-lyrics-for-a-start-up.html
so may be something in this config that's messing it up..

I'll take a look at how genius does it.. it looks like they're using just using a frame and little url rewriting, which has its trade-offs.

**Comment by jeremydean** [comment]
new to the team, but noticed this issue as well. at genius we had "genius.it/" which was easy and rolls off the tongue, "genius it!"

it's more practical and brandable to use 

"via.hypothes.is/"
 
as opposed to 

"via.hypothes.is/h/"

i can actually remember that much and prepend manually. AND i can tell someone, "check out that page *via hypothesis*".

**Comment by tilgovi** [comment]
@ikreymer we don't actually need any code changes here if you want to preserve the ability of the app to have other routes in it, which is fine.

I do need to know how either uwsgi or the wsgi framework (is it just wsgiref?) can be told about the script base path. Then I could just consider anything other than /h "internal" and reverse proxy via.hypothes.is with /h as a base.

**Comment by tilgovi** [comment]
If we do this I'll probably be serving permanent redirects from /h -> / for any old links that are out there and we reverse proxy everything in a web tier anyway, so it's not complicating things really.

**Comment by ikreymer** [comment]
The latest dev branch of pywb should be able to support this actually, I was getting ready to release it but let me do some more tests.. It may just sense to upgrade pywb to the latest version for via.

Also, unrelated but to simplify things: perhaps we should put all issues on your Via fork. I can transfer ownership and maybe you can add me to a team so I have access to it there as well.

re: wsgi, there's the standard SCRIPT_NAME and PATH_INFO wsgi env fields.. usually i think they're modified to 'mount' an app at a subpath (http://uwsgi-docs.readthedocs.org/en/latest/Nginx.html) however in this case we're sort of doing the opposite.. Then there's also the /static/ path which should be excluded from all this..

It's up to you, but I'll test latest pywb to see if can just switch to that..

**Comment by ikreymer** [comment]
And hi @jeremydean -- happy to see someone move from genius to hypothes.is :)

**Comment by tilgovi** [comment]
It probably does make sense to transfer it. I don't imagine there's a good reason for us to be "downstream" of a project that only we have deployed right now and that we'll be directly supporting.

**Comment by ikreymer** [comment]
ok. I need to have admin access on a team to be able to do the transfer:
https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

**Comment by ikreymer** [comment]
@tilgovi @dwhly @jeremydean 

Ok, here's a new version, running at root and available for merge at this branch: https://github.com/ikreymer/via/tree/dev.new-pywb-root-coll

on heroku:
https://pywb-h.herokuapp.com/
https://pywb-h.herokuapp.com/http://www.nytimes.com/
https://pywb-h.herokuapp.com/http://www.autodidacts.io/openbci-brain-basics-neurons-structure-and-biology/

It also has a simplified config (custom rewrite options instead of client side rewriting wombat.js).

It's running off the develop pywb branch currently, if all looks good, I'll push out a pywb release to coincide with this (still need to finish up changelist, etc..)

It doesn't have a /h/ -> / redirect handler, but figured that's easy enough to add on the front-end.
You may want to double check `uwsgi.ini` for your deploy also, I had to add a `venv = $(VIRTUAL_ENV)` there but not sure if you need that.

Also updated README for via.

**Comment by tilgovi** [comment]
venv shouldn't be a problem as we deploy in a heroku-like environment that should have the paths configured.

**Comment by tilgovi** [comment]
Thanks, @ikreymer let me know what my next move is.

**Comment by ikreymer** [comment]
pywb 0.9.5 has been released, and so this should be ready to go as well.
Also added the /h/ -> / 301 redirect handler as well.

**Comment by tilgovi** [comment]
@ikreymer thanks!

**Comment by tilgovi** [comment]
Also, I've made a team for this in the hypothesis org and made you an admin. You should be able to transfer it.

**Comment by ikreymer** [comment]
Bah, apparently you can't transfer ownership to an existing fork, only to a new one.. Seems kind of odd.. I emailed github support asking if they could do it.

**Comment by tilgovi** [comment]
I just deleted it.

**Comment by tilgovi** [comment]
You should now be able to?

**Comment by ikreymer** [comment]
Oh you did... yeah, i should, but there were open issues in that one.. oh well..

**Comment by tilgovi** [comment]
Huh?

**Comment by tilgovi** [comment]
Ohh... didn't think about that. Sorry.

**Comment by tilgovi** [comment]
I'll see what I can recover from my email history.

**Comment by tilgovi** [comment]
Is it possible to transfer now?

**Comment by tilgovi** [comment]
Seems like it :)

**Comment by tilgovi** [comment]
I made an attempt to migrate all the issues I could based on my email history.

Thanks, @ikreymer.
